apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: sses-ambulance-ufe-content
spec:
  microFrontend: sses-ambulance-ufe
  element: sses-ambulance-wl-list
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?sses-ambulance-wl(/.*)?$"