apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: sses-ambulance-ufe-content
spec:
  microFrontend: sses-ambulance-ufe
  element: sses-ambulance-wl-app
  attributes:
    - name: api-base
      value: http://localhost:30081/api
    - name: ambulance-id
      value: bobulova
    - name: base-path
      value: /sses-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?sses-ambulance-wl(/.*)?$"